"""Print the content-level test inventory across native, python, and live layers."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from emule_test_harness import test_inventory  # noqa: E402


def build_parser() -> argparse.ArgumentParser:
    """Builds the command-line parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="Emit the full machine-readable catalog.")
    parser.add_argument("--markdown", action="store_true", help="Emit the catalog as a Markdown document.")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Runs the inventory reporter."""

    args = build_parser().parse_args(argv)
    inv = test_inventory.build_test_inventory()
    if args.json:
        print(json.dumps(inv, indent=2))
        return 0
    text = render_markdown(inv) if args.markdown else render_text(inv)
    print(text)
    return 0


def render_text(inv: dict) -> str:
    """Renders a compact terminal summary of the catalog."""

    r = inv["rollups"]
    lines = [
        "Test inventory",
        "",
        f"Native:  {r['nativeSuiteCount']} suites / {r['nativeFileCount']} files / {r['nativeCaseCount']} cases"
        f"  ({r['nativeDormantSuiteCount']} dormant suites)",
        f"Python:  {r['pythonModuleCount']} harness modules ({r['pythonSelfTestCount']} self-test a script)",
        f"Live:    {r['liveSuiteCount']} suites ({r['liveDefaultEnabledCount']} default-enabled)",
        "",
        "Native suites (suite / files / cases / runBy)",
        "-------------------------------------------------------------",
    ]
    for s in inv["layers"]["native"]["suites"]:
        lines.append(f"  {s['suite']:34}  {s['fileCount']:>3}  {s['caseCount']:>4}  {s['runBy']}")
    lines += ["", "Live suites (name / category / stress / default / profiles)", "-" * 61]
    for s in inv["layers"]["liveE2e"]["suites"]:
        default = "on " if s["defaultEnabled"] else "off"
        lines.append(
            f"  {s['name']:34}  {s['category']:<9}  {s['stressClass']:<8}  {default}  {len(s['profiles'])}"
        )
    return "\n".join(lines)


def render_markdown(inv: dict) -> str:
    """Renders the catalog as a Markdown document body."""

    r = inv["rollups"]
    out = [
        "# Test Inventory (generated)",
        "",
        "Generated by `scripts/show-test-inventory.py --markdown`. Do not edit by hand.",
        "",
        "## Totals",
        "",
        f"- **Native:** {r['nativeSuiteCount']} doctest suites, {r['nativeFileCount']} files, "
        f"{r['nativeCaseCount']} cases - {r['nativeDormantSuiteCount']} suites are dormant "
        "(reached only via `test native --suite-name`).",
        f"- **Python harness:** {r['pythonModuleCount']} modules, {r['pythonSelfTestCount']} self-test a live script.",
        f"- **Live-e2e:** {r['liveSuiteCount']} suites, {r['liveDefaultEnabledCount']} default-enabled.",
        "",
        "## Native doctest suites",
        "",
        "| Suite | Files | Cases | Run by |",
        "| --- | ---: | ---: | --- |",
    ]
    for s in inv["layers"]["native"]["suites"]:
        out.append(f"| `{s['suite']}` | {s['fileCount']} | {s['caseCount']} | {s['runBy']} |")
    out += [
        "",
        "## Live-e2e suites",
        "",
        "| Suite | Category | Stress | Scope | Default | Profiles | Verifies |",
        "| --- | --- | --- | --- | --- | ---: | --- |",
    ]
    for s in inv["layers"]["liveE2e"]["suites"]:
        default = "yes" if s["defaultEnabled"] else "no"
        profiles = len(s["profiles"])
        out.append(
            f"| `{s['name']}` | {s['category']} | {s['stressClass']} | {s['networkScope']} | "
            f"{default} | {profiles} | {s['verifies']} |"
        )
    out += [
        "",
        "## Python-harness modules (self-test mapping)",
        "",
        "| Module | LOC | Self-tests script |",
        "| --- | ---: | --- |",
    ]
    for m in inv["layers"]["pythonHarness"]["modules"]:
        out.append(f"| `{m['module']}` | {m['loc']} | {m['selfTestsScript'] or '(none)'} |")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    raise SystemExit(main())
